In [1]:
import boto3
import pandas as pd
import io
import pymysql

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *

In [21]:
# Connect to RDS
endpoint = 'my-db.co9whbkecuet.us-east-1.rds.amazonaws.com'
username = 'admin'
password = 'Password1!'
database = 'SALES_DB'
connection = pymysql.connect(host=endpoint, user=username, passwd=password)

In [22]:
# setup env - create tables
cur = connection.cursor()

# Use all the SQL you like
# cur.execute("CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
# cur.execute("USE airflow_db")
# cur.execute("CREATE USER 'airflow_user' IDENTIFIED BY 'airflow_pass';")
# cur.execute("GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user';")
cur.execute("SHOW DATABASES")

# cur.execute("SHOW TABLES")
# cur.execute(" \
#                 CREATE TABLE IF NOT EXISTS SALES ( \
#                 ORDER_ID INT(12) NOT NULL, \
#                 QTY_ORDERED INT(100), \
#                 PRICE_PER DECIMAL(6,2), \
#                 SALES DECIMAL(12,2), \
#                 ORDER_DATE DATE \
#                 ); \
#             ")
# cur.execute("DESCRIBE SALES")    

# cur.execute("CREATE TABLE IF NOT EXISTS SALES_SUM ( \
#     SALES_TOTAL_ID INT AUTO_INCREMENT, \
#     SALES_TOTAL DECIMAL(10,2), \
#     PRIMARY KEY (SALES_TOTAL_ID) \
#     );")

#cur.execute("insert into SALES_SUM (SALES_TOTAL) values (4211.20);")

# cur.execute("select * from SALES_SUM;")

connection.commit()
# cur.execute("DELETE FROM SALES_SUM")
# connection.commit()
# print all the first cell of all the rows
for row in cur.fetchall():
    print(row)

connection.close()

('SALES_DB',)
('airflow_db',)
('information_schema',)
('mysql',)
('performance_schema',)

In [33]:
#TEST
import sqlalchemy
import pandas as pd 
from sqlalchemy.orm import sessionmaker
from sqlalchemy import *
import requests
import json
from datetime import datetime
import datetime
import sqlite3
import pymysql


# Generate your token here:  https://developer.spotify.com/console/get-recently-played/
# Note: You need a Spotify account (can be easily created for free)

def check_if_valid_data(df: pd.DataFrame) -> bool:
    # Check if dataframe is empty
    if df.empty:
        print("No songs downloaded. Finishing execution")
        return False 

    # Primary Key Check
    if pd.Series(df['played_at']).is_unique:
        pass
    else:
        raise Exception("Primary Key check is violated")

    # Check for nulls
    if df.isnull().values.any():
        raise Exception("Null values found")

    # Check that all timestamps are of yesterday's date
#     yesterday = datetime.datetime.now() - datetime.timedelta(days=1)
#     yesterday = yesterday.replace(hour=0, minute=0, second=0, microsecond=0)

#     timestamps = df["timestamp"].tolist()
#     for timestamp in timestamps:
#         if datetime.datetime.strptime(timestamp, '%Y-%m-%d') != yesterday:
#             raise Exception("At least one of the returned songs does not have a yesterday's timestamp")

    return True

In [34]:
DATABASE_LOCATION = "mysql+pymysql://airflow_user:airflow_pass@my-db.co9whbkecuet.us-east-1.rds.amazonaws.com:3306/airflow_db"
USER_ID = '22xzv4gulalicawnisxrbiyna'
TOKEN = 'BQCkoBVw9C0oiyexpxdeSOhcUk83Vn3a0LhuVfNo8vBB-6I5dQsOxuTWGAD8DEQ8Z8lkpdC1CX9GKcGECCVAU_auIeztb2PbBa76HlNh91yL38uPsRzqt4-2cUpRb32OIOxK7lGpqpb8UVGEN59c3W4cc54bTxsbQWHI6LBZ'

  # Extract part of the ETL process

headers = {
    "Accept" : "application/json",
    "Content-Type" : "application/json",
    "Authorization" : "Bearer {token}".format(token=TOKEN)
}

# Convert time to Unix timestamp in miliseconds      
today = datetime.datetime.now()
yesterday = today - datetime.timedelta(days=1)
yesterday_unix_timestamp = int(yesterday.timestamp()) * 1000

# Download all songs you've listened to "after yesterday", which means in the last 24 hours      
r = requests.get("https://api.spotify.com/v1/me/player/recently-played?after={time}".format(time=yesterday_unix_timestamp), headers = headers)

data = r.json()

In [35]:
song_names = []
artist_names = []
played_at_list = []
timestamps = []

# Extracting only the relevant bits of data from the json object      
for song in data["items"]:
    song_names.append(song["track"]["name"])
    artist_names.append(song["track"]["album"]["artists"][0]["name"])
    played_at_list.append(song["played_at"])
    timestamps.append(song["played_at"][0:10])

# Prepare a dictionary in order to turn it into a pandas dataframe below       
song_dict = {
    "song_name" : song_names,
    "artist_name": artist_names,
    "played_at" : played_at_list,
    "timestamp" : timestamps
}

song_df = pd.DataFrame(song_dict, columns = ["song_name", "artist_name", "played_at", "timestamp"])

# Validate
if check_if_valid_data(song_df):
    print("Data valid, proceed to Load stage")

# Load


engine = sqlalchemy.create_engine(DATABASE_LOCATION)
#conn = sqlite3.connect('my_played_tracks.sqlite')
print("TEST")
endpoint = 'my-db.co9whbkecuet.us-east-1.rds.amazonaws.com'
username = 'airflow_user'
password = 'airflow_pass'
database = 'airflow_db'
conn = pymysql.connect(host=endpoint, user=username, passwd=password, port=3306)

cursor = conn.cursor()

sql_query = """
CREATE TABLE IF NOT EXISTS my_played_tracks(
    song_name VARCHAR(200),
    artist_name VARCHAR(200),
    played_at VARCHAR(200),
    timestamp VARCHAR(200),
    CONSTRAINT primary_key_constraint PRIMARY KEY (played_at)
)
"""

cursor.execute(sql_query)
print("Opened database successfully")

try:
    song_df.to_sql("my_played_tracks", engine, index=False, if_exists='append')
except:
    print("Data already exists in the database")

conn.close()
print("Close database successfully")

Data valid, proceed to Load stage

OperationalError: (1046, 'No database selected')